#################
# Camera Server #
#################
camera_server:
    # Video feed options
    stream_type: "UDP" # Supports HTTP or UDP
    stream_port: 5600
    stream_address: "192.168.2.1"

    # HTTP Broadcast options
    broadcast_port: 8080
    broadcast_address: "/"
    number_threads: 2
    image_quality: 30   # Ints from 0<->100 %