data_serializer:
    vehicle_id: 5

dmac2farol:
    # false, vehicle acts as an achor, estimates other vehicles position 
    # true, vehicle estimates its own position with respect to an anchor   
    fix_type: true
    # true, real vehcile
    # false, simulation scenarios with evo emulator
    real: true
    installation_matrix: [-0.7854, 0, 3.1415]